// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQxlcmuJzKSWLrDZ0aDTguP7zSHaf7j-I',
    appId: '1:650955939778:web:d63e1da018cb367c42005b',
    messagingSenderId: '650955939778',
    projectId: 'godseye-85466',
    authDomain: 'godseye-85466.firebaseapp.com',
    storageBucket: 'godseye-85466.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnOdOIj2MWzLE0f5gjlayhHWMlwkVtCWg',
    appId: '1:650955939778:android:2107d36580fc514142005b',
    messagingSenderId: '650955939778',
    projectId: 'godseye-85466',
    storageBucket: 'godseye-85466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZo0SkpWzsrCy-fuSC8DVPwUi5UpIkjOU',
    appId: '1:650955939778:ios:f3743b98e6d6b39542005b',
    messagingSenderId: '650955939778',
    projectId: 'godseye-85466',
    storageBucket: 'godseye-85466.appspot.com',
    iosBundleId: 'com.example.fakecurrency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZo0SkpWzsrCy-fuSC8DVPwUi5UpIkjOU',
    appId: '1:650955939778:ios:f3743b98e6d6b39542005b',
    messagingSenderId: '650955939778',
    projectId: 'godseye-85466',
    storageBucket: 'godseye-85466.appspot.com',
    iosBundleId: 'com.example.fakecurrency',
  );
}
